/*  BACnetPropertyIdentifier Enumeration
 *  Copyright (C) 2010 Loren Van Spronsen
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace BACnet.ProtocolTypes
{
    /* This is a little ugly
     * most of the other enumerations are just sorted
     * by the integer values */
    public enum BACnetPropertyIdentifier
    {
        AcceptedModes = 175,
        AckedTransitions = 0,
        AckRequired = 1,
        Action = 2,
        ActionText = 3,
        ActiveText = 4,
        ActiveVtSessions = 5,
        ActiveCovSubscriptions = 152,
        ActualShedLevel = 212,
        AdjustValue = 176,
        AlarmValue = 6,
        AlarmValues = 7,
        AlignIntervals = 193,
        All = 8,
        AllWritesSuccessfull = 9,
        ApduSegmentTimeout = 10,
        ApduTimeout = 11,
        ApplicationSoftwareVersion = 12,
        Archive = 13,
        AttemptedSamples = 124,
        AutoSlaveDiscovery = 169,
        AverageValue = 125,
        BackupFailureTimeout = 153,
        Bias = 14,
        BufferSize = 126,
        ChangeOfStateCount = 15,
        ChangeOfStateTime = 16,
        ClientCovIncrement = 127,
        ConfigurationFiles = 154,
        ControlledVariableReference = 19,
        ControlledVariableUnits = 20,
        ControlledVariableValue = 21,
        Count = 177,
        CountBeforeChange = 178,
        CountChangeTime = 179,
        CovIncrement = 22,
        CovPeriod = 180,
        CovResubscriptionInterval = 128,
        CurrentNotifyTime=129,
        DatabaseRevision = 155,
        DateList = 23,
        DaylightSavingsStatus = 24,
        Deadband = 25,
        DerivativeConstant = 26,
        DerivativeConstantUnits = 27,
        Description = 28,
        DescriptionOfHalt = 29,
        DeviceAddressBinding = 30,
        DeviceType = 31,
        DirectReading = 156,
        DoorAlarmState = 226,
        DoorExtendedPulseTime = 227,
        DoorMembers = 228,
        DoorOpenTooLongTime = 229,
        DoorPulseTime = 230,
        DoorStatus = 231,
        DoorUnlockDelayTime = 232,
        DutyWindow = 213,
        EffectivePeriod = 32,
        ElapsedActiveTime = 33,
        Enable = 133,
        ErrorLimit = 34,
        EventEnable = 35,
        EventState = 36,
        EventTimeStamps = 130,
        EventType = 37,
        EventParameters = 83,
        ExceptionSchedule = 38,
        ExpectedShedLevel = 214,
        FaultValues = 39,
        FeedbackValue = 40,
        FileAccessMethod = 41,
        FileSize = 42,
        FileType = 43,
        FirmwareRevision = 44,
        FullDutyBaseline = 215,
        HighLimit = 45,
        InactiveText = 46,
        InProcess = 47,
        InputReference = 181,
        InstanceOf = 48,
        IntegralConstant = 49,
        IntegralConstantUnits = 50,
        IntervalOffset = 195,
        IssueConfirmedNotifications=51,
        LastNotifyRecord = 173,
        LastRestartReason = 196,
        LastRestoreTime = 157,
        LifeSafetyAlarmValues = 166,
        LimitEnable = 52,
        LimitMonitoringInterval = 182,
        ListOfGroupMembers = 53,
        ListOfObjectPropertyReferences = 54,
        ListOfSessionKeys = 55,
        LocalDate = 56,
        LocalTime = 57,
        Location = 58,
        LockStatus = 233,
        LogBuffer = 131,
        LogDeviceObjectProperty = 132,
        LogInterval = 134,
        LoggingObject = 183,
        LoggingRecord = 184,
        LoggingType = 197,
        LowLimit = 59,
        MaintenanceRequired = 158,
        ManipulatedVariableReference = 60,
        ManualSlaveAddressBinding = 170,
        MaskedAlarmValues = 234,
        MaximumOutput = 61,
        MaximumValue = 135,
        MaximumValueTimestamp = 149,
        MaxApduLengthAccepted = 62,
        MaxInfoFrames = 63,
        MaxMaster = 64,
        MaxPresValue = 65,
        MaxSegmentsAccepted = 167,
        MemberOf = 159,
        MinimumOffTime = 66,
        MinimumOnTime = 67,
        MinimumOutput = 68,
        MinimumValue = 136,
        MinimumValueTimestamp = 150,
        MinPresValue = 69,
        Mode = 160,
        ModelName = 70,
        ModificationDate = 71,
        NodeSubtype = 207,
        NodeType = 208,
        NotificationClass = 17,
        NotificationThreshold = 137,
        NotifyType = 72,
        NumberOfApduRetries = 73,
        NumberOfStates = 74,
        ObjectIdentifier = 75,
        ObjectList = 76,
        ObjectName = 77,
        ObjectPropertyReference = 78,
        ObjectType = 79,
        OperationExpected = 161,
        Optional = 80,
        OutOfService = 81,
        OutputUnits = 82,
        Polarity = 84,
        Prescale = 185,
        PresentValue = 85,
        PreviousNotifyTime=138,
        Priority = 86,
        PulseRate = 186,
        PriorityArray = 87,
        PriorityForWriting = 88,
        ProcessIdentifier = 89,
        ProfileName = 168,
        ProgramChange = 90,
        ProgramLocation = 91,
        ProgramState = 92,
        ProportionalConstant = 93,
        ProportionalConstantUnits = 94,
        ProtocolConformanceClass=95,
        ProtocolObjectTypesSupported = 96,
        ProtocolRevision = 139,
        ProtocolServicesSupported = 97,
        ProtocolVersion = 98,
        ReadOnly = 99,
        ReasonForHalt = 100,
        Recipient=101,
        RecipientList = 102,
        RecordsSinceNotification = 140,
        RecordCount = 141,
        Reliability = 103,
        RelinquishDefault = 104,
        RequestedShedLevel = 218,
        Required = 105,
        Resolution = 106,
        RestartNotificationRecipients = 202,
        Scale = 187,
        ScaleFactor = 188,
        ScheduleDefault = 174,
        SecuredStatus = 235,
        SegmentationSupported = 107,
        Setpoint = 108,
        SetpointReference = 109,
        Setting = 162,
        ShedDuration = 219,
        ShedLevelDescriptions = 220,
        ShedLevels = 221,
        Silenced = 163,
        SlaveAddressBinding = 171,
        SlaveProxyEnable = 172,
        StartTime = 142,
        StateDescription = 222,
        StateText = 110,
        StatusFlags = 111,
        StopTime = 143,
        StopWhenFull = 144,
        StructuredObjectList = 209,
        SubordinateAnnotations = 210,
        SubordinateList = 211,
        SystemStatus = 112,
        TimeDelay = 113,
        TimeOfActiveTimeReset = 114,
        TimeOfDeviceRestart = 203,
        TimeOfStateCountReset = 115,
        TimeSynchronizationInterval = 204,
        TimeSynchronizationRecipients = 116,
        TotalRecordCount = 145,
        TrackingValue = 164,
        Trigger = 205,
        Units = 117,
        UpdateInterval = 118,
        UpdateTime = 189,
        UtcOffset = 119,
        UtcTimeSynchronizationRecipients = 206,
        ValidSamples = 146,
        ValueBeforeChange = 190,
        ValueSet = 191,
        ValueChangeTime = 192,
        VarianceValue = 151,
        VendorIdentifier = 120,
        VendorName = 121,
        VtClassesSupported = 122,
        WeeklySchedule = 123,
        WindowInterval = 147,
        WindowSamples = 148,
        ZoneMembers = 165
    }
}
